version: "3.8"
services:
  frontend:
    build: .
    container_name: fabric-scan-ui
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
